Copying from consul

diff --git a/modules/install-nomad/install-nomad b/modules/install-nomad/install-nomad
--- a/modules/install-nomad/install-nomad
+++ b/modules/install-nomad/install-nomad
@@ -3,19 +3,17 @@
 # operating systems:
 #
 # 1. Ubuntu 16.04
-# 2. Ubuntu 18.04
-# 3. Amazon Linux
+# 1. Ubuntu 18.04
+# 1. Amazon Linux 2
 
 set -e
 
 readonly DEFAULT_INSTALL_PATH="/opt/nomad"
 readonly DEFAULT_NOMAD_USER="nomad"
+readonly DOWNLOAD_PACKAGE_PATH="/tmp/nomad.zip"
 
 readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 readonly SYSTEM_BIN_DIR="/usr/local/bin"
-
-readonly SUPERVISOR_DIR="/etc/supervisor"
-readonly SUPERVISOR_CONF_DIR="$SUPERVISOR_DIR/conf.d"
 
 readonly SCRIPT_NAME="$(basename "$0")"
 
@@ -23,44 +21,45 @@ function print_usage {
   echo
   echo "Usage: install-nomad [OPTIONS]"
   echo
-  echo "This script can be used to install Nomad and its dependencies. This script has been tested with Ubuntu 16.04, Ubuntu 18.04 and Amazon Linux."
+  echo "This script can be used to install Nomad and its dependencies. This script has been tested with Ubuntu 16.04 and Amazon Linux 2."
   echo
   echo "Options:"
   echo
-  echo -e "  --version\t\tThe version of Nomad to install. Required."
+  echo -e "  --version\t\tThe version of Nomad to install. Optional if download-url is provided."
+  echo -e "  --download-url\t\tUrl to exact Nomad package to be installed. Optional if version is provided."
   echo -e "  --path\t\tThe path where Nomad should be installed. Optional. Default: $DEFAULT_INSTALL_PATH."
   echo -e "  --user\t\tThe user who will own the Nomad install directories. Optional. Default: $DEFAULT_NOMAD_USER."
   echo
   echo "Example:"
   echo
-  echo "  install-nomad --version 0.5.4"
+  echo "  install-nomad --version 1.2.2"
 }
 
 function log {
-  local readonly level="$1"
-  local readonly message="$2"
-  local readonly timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+  local -r level="$1"
+  local -r message="$2"
+  local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
   >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
 }
 
 function log_info {
-  local readonly message="$1"
+  local -r message="$1"
   log "INFO" "$message"
 }
 
 function log_warn {
-  local readonly message="$1"
+  local -r message="$1"
   log "WARN" "$message"
 }
 
 function log_error {
-  local readonly message="$1"
+  local -r message="$1"
   log "ERROR" "$message"
 }
 
 function assert_not_empty {
-  local readonly arg_name="$1"
-  local readonly arg_value="$2"
+  local -r arg_name="$1"
+  local -r arg_value="$2"
 
   if [[ -z "$arg_value" ]]; then
     log_error "The value for '$arg_name' cannot be empty"
@@ -69,39 +68,41 @@ function assert_not_empty {
   fi
 }
 
-# Install steps are based on: http://unix.stackexchange.com/a/291098/215969
-function install_supervisord_debian {
-  sudo apt-get install -y supervisor
-  sudo update-rc.d supervisor defaults
+function assert_either_or {
+  local -r arg1_name="$1"
+  local -r arg1_value="$2"
+  local -r arg2_name="$3"
+  local -r arg2_value="$4"
 
-  create_supervisor_config
-  sudo systemctl enable supervisor
+  if [[ -z "$arg1_value" && -z "$arg2_value" ]]; then
+    log_error "Either the value for '$arg1_name' or '$arg2_name' must be passed, both cannot be empty"
+    print_usage
+    exit 1
+  fi
 }
 
-# Install steps are based on: http://stackoverflow.com/a/31576473/483528
-function install_supervisord_amazon_linux {
-  sudo pip install supervisor
+# A retry function that attempts to run a command a number of times and returns the output
+function retry {
+  local -r cmd="$1"
+  local -r description="$2"
 
-  # On Amazon Linux, /usr/local/bin is not in PATH for the root user, so we add symlinks to /usr/bin, which is in PATH
-  if [[ ! -f "/usr/bin/supervisorctl" ]]; then
-    sudo ln -s /usr/local/bin/supervisorctl /usr/bin/supervisorctl
-  fi
-  if [[ ! -f "/usr/bin/supervisord" ]]; then
-    sudo ln -s /usr/local/bin/supervisord /usr/bin/supervisord
-  fi
+  for i in $(seq 1 5); do
+    log_info "$description"
 
-  sudo cp "$SCRIPT_DIR/supervisor-initd-script.sh" "/etc/init.d/supervisor"
-  sudo chmod a+x /etc/init.d/supervisor
-  sudo mkdir -p /var/log/supervisor
+    # The boolean operations with the exit status are there to temporarily circumvent the "set -e" at the
+    # beginning of this script which exits the script immediatelly for error status while not losing the exit status code
+    output=$(eval "$cmd") && exit_status=0 || exit_status=$?
+    log_info "$output"
+    if [[ $exit_status -eq 0 ]]; then
+      echo "$output"
+      return
+    fi
+    log_warn "$description failed. Will sleep for 10 seconds and try again."
+    sleep 10
+  done;
 
-  create_supervisor_config
-  sudo chkconfig --add supervisor
-  sudo chkconfig supervisor on
-}
-
-function create_supervisor_config {
-  sudo mkdir -p "$SUPERVISOR_CONF_DIR"
-  sudo cp "$SCRIPT_DIR/supervisord.conf" "$SUPERVISOR_DIR/supervisord.conf"
+  log_error "$description failed after 5 attempts."
+  exit $exit_status
 }
 
 function has_yum {
@@ -118,10 +119,9 @@ function install_dependencies {
   if $(has_apt_get); then
     sudo apt-get update -y
     sudo apt-get install -y awscli curl unzip jq
-    install_supervisord_debian
   elif $(has_yum); then
+    sudo yum update -y
     sudo yum install -y aws curl unzip jq
-    install_supervisord_amazon_linux
   else
     log_error "Could not find apt-get or yum. Cannot install dependencies on this OS."
     exit 1
@@ -129,12 +129,12 @@ function install_dependencies {
 }
 
 function user_exists {
-  local readonly username="$1"
+  local -r username="$1"
   id "$username" >/dev/null 2>&1
 }
 
 function create_nomad_user {
-  local readonly username="$1"
+  local -r username="$1"
 
   if $(user_exists "$username"); then
     echo "User $username already exists. Will not create again."
@@ -145,41 +145,49 @@ function create_nomad_user {
 }
 
 function create_nomad_install_paths {
-  local readonly path="$1"
-  local readonly username="$2"
+  local -r path="$1"
+  local -r username="$2"
 
   log_info "Creating install dirs for Nomad at $path"
   sudo mkdir -p "$path"
   sudo mkdir -p "$path/bin"
   sudo mkdir -p "$path/config"
   sudo mkdir -p "$path/data"
-  sudo mkdir -p "$path/log"
+  sudo mkdir -p "$path/tls/ca"
 
   log_info "Changing ownership of $path to $username"
   sudo chown -R "$username:$username" "$path"
 }
 
-function install_binaries {
-  local readonly version="$1"
-  local readonly path="$2"
-  local readonly username="$3"
+function fetch_binary {
+  local -r version="$1"
+  local download_url="$2"
 
-  local readonly url="https://releases.hashicorp.com/nomad/${version}/nomad_${version}_linux_amd64.zip"
-  local readonly download_path="/tmp/nomad_${version}_linux_amd64.zip"
-  local readonly bin_dir="$path/bin"
-  local readonly nomad_dest_path="$bin_dir/nomad"
-  local readonly run_nomad_dest_path="$bin_dir/run-nomad"
+  if [[ -z "$download_url" && -n "$version" ]];  then
+    download_url="https://releases.hashicorp.com/nomad/${version}/nomad_${version}_linux_amd64.zip"
+  fi
 
-  log_info "Downloading Nomad $version from $url to $download_path"
-  curl -o "$download_path" "$url"
-  unzip -d /tmp "$download_path"
+  retry \
+    "curl -o '$DOWNLOAD_PACKAGE_PATH' '$download_url' --location --silent --fail --show-error" \
+    "Downloading Nomad to $DOWNLOAD_PACKAGE_PATH"
+}
+
+function install_binary {
+  local -r install_path="$1"
+  local -r username="$2"
+
+  local -r bin_dir="$install_path/bin"
+  local -r nomad_dest_path="$bin_dir/nomad"
+  local -r run_nomad_dest_path="$bin_dir/run-nomad"
+
+  unzip -d /tmp "$DOWNLOAD_PACKAGE_PATH"
 
   log_info "Moving Nomad binary to $nomad_dest_path"
   sudo mv "/tmp/nomad" "$nomad_dest_path"
   sudo chown "$username:$username" "$nomad_dest_path"
   sudo chmod a+x "$nomad_dest_path"
 
-  local readonly symlink_path="$SYSTEM_BIN_DIR/nomad"
+  local -r symlink_path="$SYSTEM_BIN_DIR/nomad"
   if [[ -f "$symlink_path" ]]; then
     log_info "Symlink $symlink_path already exists. Will not add again."
   else
@@ -195,6 +203,7 @@ function install_binaries {
 
 function install {
   local version=""
+  local download_url=""
   local path="$DEFAULT_INSTALL_PATH"
   local user="$DEFAULT_NOMAD_USER"
 
@@ -204,6 +213,10 @@ function install {
     case "$key" in
       --version)
         version="$2"
+        shift
+        ;;
+      --download-url)
+        download_url="$2"
         shift
         ;;
       --path)
@@ -228,7 +241,7 @@ function install {
     shift
   done
 
-  assert_not_empty "--version" "$version"
+  assert_either_or "--version" "$version" "--download-url" "$download_url"
   assert_not_empty "--path" "$path"
   assert_not_empty "--user" "$user"
 
@@ -237,9 +250,16 @@ function install {
   install_dependencies
   create_nomad_user "$user"
   create_nomad_install_paths "$path" "$user"
-  install_binaries "$version" "$path" "$user"
 
-  log_info "Nomad install complete!"
+  fetch_binary "$version" "$download_url"
+  install_binary "$path" "$user"
+
+  if command -v nomad; then
+    log_info "Nomad install complete!";
+  else
+    log_info "Could not find nomad command. Aborting.";
+    exit 1;
+  fi
 }
 
 install "$@"
